"""empty message

Revision ID: 4502a31dd702
Revises: 3f7113991f65
Create Date: 2021-06-14 08:21:19.173008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4502a31dd702"
down_revision = "3f7113991f65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("tags", sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "tags")
    # ### end Alembic commands ###
